{
 "title": "db_overview_ts",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "select distinct dbname from backends ;"
   }
  ]
 },
 "panels": [
  {
   "title": "DB age",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  now() as time,\n  age(datfrozenxid)\nFROM\n  pg_database;\n"
    }
   ]
  },
  {
   "title": "DB size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__time(time),\n  size_b\nFROM\n  db_stats\nWHERE\ndbname = '$dbname'and\n  $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Approx Bloat",
   "type": "singlestat",
   "description": "Based on pgstattuple_approx, for tables >800KB",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "rawSql": "SELECT\n  $__time(time),\n  approx_free_percent\nFROM\n  table_bloat_approx_summary\nWHERE\ndbname = '$dbname'and\n  $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "cpu_load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time),\n  load_5min,\n  load_1min,\n  load_15min\nFROM\n  cpu_load\nWHERE\ndbname = '$dbname'and\n  $__timeFilter(time)\n  \n"
    }
   ]
  },
  {
   "title": "sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__time(time),\n  active,\n  idle,\n  idleintransaction,\n  waiting\nFROM\n  backends\nWHERE\n\tdbname = '$dbname'\nand\n\t$__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Tuple IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select \n\ttime,\n\ttup_updated - lag(tup_updated,10) over ( order by time ) as tup_updated,\n\ttup_inserted - lag(tup_inserted,10) over ( order by time ) as tup_inserted,\n\ttup_deleted - lag(tup_deleted,10) over ( order by time ) as tup_deleted\nfrom db_stats\nWHERE\ndbname = '$dbname'and\n  $__timeFilter(time);"
    }
   ]
  },
  {
   "title": "backends",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__time(time),\n  deadlocks,\n  numbackends,\n  temp_files\nFROM\n  db_stats\nWHERE\n\tdbname = '$dbname'\nand\n\t$__timeFilter(time)"
    }
   ]
  },
  {
   "title": "wal rate Bps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select\n\ttime,\n\txlog_location_b - lag(xlog_location_b) over (order by time) as wal_rate\nfrom wal\nWHERE\n\tdbname = '$dbname'\nand\n\t$__timeFilter(time)"
    }
   ]
  },
  {
   "title": "ratios",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select\n\ttime,\n\tblks_hit*100/(0.0+blks_hit+blks_read) as blks_hit_ratio,\n\txact_rollback*100/(0.0+xact_rollback+xact_commit) as xact_rollback_ratio\nfrom\n\tdb_stats\nWHERE\n\tdbname = '$dbname'\nand\n\t$__timeFilter(time)"
    }
   ]
  }
 ]
}