FROM ubuntu:16.04

RUN apt-get -q update && apt-get -qy install wget git

###
### Install Go
###

RUN wget -q https://storage.googleapis.com/golang/go1.9.2.linux-amd64.tar.gz \
    && tar -C /usr/local -xzf go1.9.2.linux-amd64.tar.gz \
    && rm go1.9.2.linux-amd64.tar.gz \
    && export PATH=$PATH:/usr/local/go/bin \
    && echo 'export PATH=$PATH:/usr/local/go/bin' >> /root/.bashrc

###
### add pgwatch2 source and configure installed components
###

ADD pgwatch2 /pgwatch2

RUN cd /pgwatch2 && bash build_gatherer.sh \
    && useradd -d /pgwatch2 pgwatch2 \
    && chown -R pgwatch2 /pgwatch2

USER pgwatch2

CMD ["/pgwatch2/pgwatch2", "--help"]
ENTRYPOINT ["/pgwatch2/pgwatch2"]
