{
 "title": "pgbouncer",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dbname",
    "query": "select distinct dbname from pgbouncer_stats ;"
   }
  ]
 },
 "panels": [
  {
   "title": "QPS",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  time,\n  avg_query_count\nFROM\n  pgbouncer_stats\nwhere\n  dbname = '$dbname'\nand\n  $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "avg_query_time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "format": "µs",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__time(time),\n  avg_query_time\nFROM\n  pgbouncer_stats\nWHERE\n  dbname = '$dbname'\nand\n  $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "avg_wait_time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "format": "µs",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__time(time),\n  avg_wait_time\nFROM\n  pgbouncer_stats\nWHERE\n  dbname = '$dbname'\nand\n  $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "pgb_avg_query_time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "rawSql": "SELECT\n  $__time(time),\n  avg_query_time\nFROM\n  pgbouncer_stats\nWHERE\ndbname = '$dbname'and\n  $__timeFilter(time)\n  \n"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  time,\n  avg_query_count\nFROM\n  pgbouncer_stats\nwhere\n  dbname = '$dbname'\nand\n  $__timeFilter(time)"
    }
   ]
  }
 ]
}